#!/usr/bin/env bash
update_ws_icons() {
	local ws="$1"
	local app_num=1
	while IFS= read -r app_id; do
		local child="space.$ws.$app_num"
		sketchybar --query "$child" >/dev/null 2>&1 || sketchybar --add item "$child" left
		sketchybar --set "$child" \
			drawing=on background.drawing=on background.image.drawing=on \
			background.image="app.$app_id"
		app_num=$((app_num + 1))
	done < <(aerospace list-windows --workspace "$ws" --format "%{app-bundle-id}")
}
