[".config/kitty/easy-session-manager"]
type = "git-repo"
url = "git@github.com:systemi-yokohama/kitty-easy-session-manager.git"
refreshPeriod = "168h"

[".config/kitty/easy-session-manager".pull]
args = ["--ff-only"]

[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
refreshPeriod = "168h"

[".oh-my-zsh".pull]
args = ["--ff-only"]

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions".pull]
args = ["--ff-only"]

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting".pull]
args = ["--ff-only"]
