#!/bin/bash

# zsh
"$HOME"/dotfiles/zsh/install

# neovim
mkdir -p "$HOME"/.config

nvim_dir="$HOME"/.config/nvim
if [ -d "$nvim_dir" ]; then
	echo "Neovim config dir already exists, skipping making alias."
else
	ln -s "$HOME"/dotfiles/nvim "$nvim_dir"
fi
