# https://github.com/roosta/i3wsr?tab=readme-ov-file

[general]
display_property = "class"
# default_icon = " "
separator = "| "

[options]
remove_duplicates = true 
no_names = false         
no_icon_names = true     
focus_fix = true         

[aliases.class]
Brave="Brave"
terminal="Terminal"
firefox="Firefox"
Alacritty="Terminal"
kitty="Terminal"
Timeshift="Timeshift"
Localsend="Localsend"
handbrake="handbrake"
Ardour="Ardour"
Nm-="Nm-"
# Fonts are inherited from i3 config
# https://www.nerdfonts.com/cheat-sheet
[icons]
Brave = "󰖟 "
Terminal= " "
Thunar=" "
Localsend=" "
Code=" "
Blender=" "
authenticator="󰢏 "
Beeper=" "
discord=" "
Arandr=" "
libreoffice-writer = " "
libreoffice-calc = " "
libreoffice-impress = " "
Timeshift=" "
Mixxx=" "
pavucontrol=" "
resolve="󰿎 "
GParted=" "
baobab=" "
bottles=" "
ONLYOFFICE=" "
resources=" "
Gsmartcontrol="󰋊 "
handbrake="󱁆 "
DiskDigger="󰜐 "
vlc="󰕼 "
Open_tv="󰟴 "
"Image Lounge"=" "
Ardour=" "
SooperLooper=" "
QjackCtl="󱎔 "
REAPER="󰽯 "
impression="󱊞 "
"Angry IP Scanner"="󰩠 "
VeraCrypt="  "
Nm-="  "
snapshot="  "
Gimp = " "
